arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Effort Controllers ---------------------------------------
  base_yaw_effort_controller:
    type: effort_controllers/JointEffortController
    joint: base_yaw
    pid: {p: 100.0, i: 0.01, d: 10.0}
  base_pitch_effort_controller:
    type: effort_controllers/JointEffortController
    joint: base_pitch
    pid: {p: 100.0, i: 0.01, d: 10.0}  
  pitch2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: pitch2
    pid: {p: 100.0, i: 0.01, d: 10.0}  
  roll1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: roll1
    pid: {p: 100.0, i: 0.01, d: 10.0}  
  pitch3_effort_controller:
    type: effort_controllers/JointEffortController
    joint: pitch3
    pid: {p: 100.0, i: 0.01, d: 10.0}  
  roll2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: roll2
    pid: {p: 100.0, i: 0.01, d: 10.0}  
  slide_finger1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: slide_finger1
    pid: {p: 100.0, i: 0.01, d: 10.0}
