camera/wide_angle       : "/wide_angle/image_color/compressed"
camera/wide_angle_dev   : "/dev/cam_ultra_wide"
camera/wide_angle_hires : "/wide_angle/camera/image_raw"

camera/arm              : "/camera_arm/image_color/compressed"
camera/arm_dev          : "/dev/arm_camera"
camera/arm_hires        : "/camera_arm/camera/image_raw"

camera/pan_tilt         : "/omnicam/image_color/compressed"
camera/pan_tilt_dev     : "/dev/econ_camera"
camera/pan_tilt_hires   : "/camera/pan_tilt/image_raw"
