camera/wide_angle       : "/wide_angle/image_mono/compressed"
camera/wide_angle_dev   : "/dev/cam_ultra_wide"
camera/wide_angle_hires : "/camera/wide_angle/image_raw"
camera/arm              : "/camera_arm/image_color/compressed"
camera/arm_dev          : "/dev/arm_camera"
camera/arm_hires        : "/camera/arm/image_raw"
camera/pan_tilt         : "/econ"
camera/pan_tilt_dev     : "/dev/econ_camera"
camera/pan_tilt_hires   : "/camera/pan_tilt/image_raw"
