#mode select:
joystick/drive_mode :           "3"
joystick/camera_mode :          "6"
joystick/arm_base_mode :        "4"
joystick/science_mode:          "5"

joystick/ackreman_moving :      "1" # motor enable
joystick/point_steer :          "3"
joystick/ackreman :             "2"

logitech/base:                  "7"
logitech/diff1:                 "9"
logitech/diff2:                 "10"
logitech/end:                   "8"

joystick/drill_on:              "hat_left"
joystick/drill_off:             "hat_right"


#cam mode
joystick/next_cam :             "hat_top"
joystick/prev_cam :             "hat_down"