#mode select:
joystick/drive_mode :           "5"
joystick/camera_mode :          "6"
joystick/arm_base_mode :        "4"

joystick/ackreman_moving :      "1" # motor enable
joystick/point_steer :          "3"
joystick/ackreman :             "2"

logitech/base:                  "7"
logitech/diff1:                 "9"
logitech/diff2:                 "10"
logitech/end:                   "8"
