#!/usr/bin/bash

if [[ -d ${ROBOTIC_PATH}/tivaware ]]; then
    export TIVA_WARE_PATH=${ROBOTIC_PATH}/tivaware
fi

if [[ -f /usr/bin/lm4flash ]]; then
    export TIVA_FLASH_EXECUTABLE=lm4flash 
fi

alias startrover='tmuxinator start rover' 

export QGST_PATH=${ROBOTIC_PATH}/rover/qt-gstreamer_lib
export RIMSTREAMER_ROOT=${ROBOTIC_PATH}/rover/rimstreamer_lib
export PATH=$PATH:$QGST_PATH/include:$QGST_PATH/lib
export PATH=$PATH:$RIMSTREAMER_ROOT/include:$RIMSTREAMER_ROOT/lib

