arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  # Position Controllers ---------------------------------------
  base_yaw_effort_controller:
    type: effort_controllers/JointEffortController
    joint: base_yaw
  base_pitch_effort_controller:
    type: effort_controllers/JointEffortController
    joint: base_pitch
  elbow_pitch_effort_controller:
    type: effort_controllers/JointEffortController
    joint: elbow_pitch
  elbow_roll_effort_controller:
    type: effort_controllers/JointEffortController
    joint: elbow_roll
  wrist_pitch_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wrist_pitch
  wrist_roll_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wrist_roll
