########################################################################
# XyzToMastAzel.srv
# 
# Returns the azimuth and elevation pointing angles that would center the 
# given mast-mounted camera (or camera pair) on the given x,y,z position.
# Also returns a success status indicating if the resulting azel is valid.
# This assumes everything is relative to rover's current position, using 
# whichever frames are specified by conversion_frames.
#
# Returned azel is a general Point type with azimuth being azel.z, elevation 
# being azel.y, and azel.x is unused.
########################################################################

geometry_msgs/Point xyz

# Which mast-mounted camera(s) would be centered on given xyz point
uint8 left_camera
uint8 right_camera
uint8 NONE=0
# No FRONT_HAZCAM on mast
# No REAR_HAZCAM on mast
uint8 NAVCAM=3
uint8 MASTCAM=4

# Which frame the xyz is specified in to which frame to compute resulting azel
uint8 conversion_frames
uint8 SITE_XYZ_TO_LL_ABS_AZEL=0
uint8 RNAV_XYZ_TO_RNAV_ABS_AZEL=1

---

# azel.z = azimuth, azel.y = elevation, azel.x is unused
geometry_msgs/Point azel

bool success
