//
// Created by David Lavoie-Boutin on 2016-03-03.
//

#ifndef ROVER_ARDUINO_PINS_ARM_H
#define ROVER_ARDUINO_PINS_ARM_H

#define NC 60

#define BASE_YAW_SS_PIN NC
#define BASE_YAW_ENABLE_PIN 1
#define BASE_YAW_DATA1_PIN 1
#define BASE_YAW_DATA2_PIN 1
#define BASE_YAW_DIRECTION_PIN 1
#define BASE_YAW_READY_PIN 1
#define BASE_YAW_DRIVE_PIN 5

#define END_EFFECTOR_SPEED_PIN 11
#define END_EFFECTOR_INA_PIN 33
#define END_EFFECTOR_INB_PIN 42
#define END_EFFECTOR_SS_PIN 27

#define PITCH_1_SPEED_PIN 12
#define PITCH_1_INA_PIN 45
#define PITCH_1_INB_PIN 39
#define PITCH_1_SS_PIN 44
#define PITCH_1_BRK_PIN 28

#define DIFF_1_LEFT_SPEED_PIN 7
#define DIFF_1_LEFT_INA_PIN 47
#define DIFF_1_LEFT_INB_PIN 41
#define DIFF_1_LEFT_SS_PIN 46
#define DIFF_1_LEFT_BRK_PIN 30

#define DIFF_1_RIGHT_SPEED_PIN 8
#define DIFF_1_RIGHT_INA_PIN 49
#define DIFF_1_RIGHT_INB_PIN 43
#define DIFF_1_RIGHT_SS_PIN 48
#define DIFF_1_RIGHT_BRK_PIN 32

#define DIFF_2_LEFT_SPEED_PIN 9
#define DIFF_2_LEFT_INA_PIN 29
#define DIFF_2_LEFT_INB_PIN 38
#define DIFF_2_LEFT_SS_PIN 23
#define DIFF_2_LEFT_BRK_PIN 34

#define DIFF_2_RIGHT_SPEED_PIN 10
#define DIFF_2_RIGHT_INA_PIN 31
#define DIFF_2_RIGHT_INB_PIN 40
#define DIFF_2_RIGHT_SS_PIN 25
#define DIFF_2_RIGHT_BRK_PIN 36

#endif //ROVER_ARDUINO_PINS_ARM_H
