##################################################
# AcquireImage Action
# Action Subscribed Topics
#   goal : AcquireImageActionGoal
#   cancel : actionlib_msgs/GoalID
# Action Published Topics
#   feedback : AcquireImageActionFeedback
#   status : actionlib_msgs/GoalStatusArray
#   result : AcquireImageActionResult
##################################################

################
###   Goal   ###
################

# goal_id: contains timestamp for request time and unique string id
actionlib_msgs/GoalID goal_id

# left_camera/right_camera: enum specifying which camera(s) to use
uint8 left_camera
uint8 right_camera
uint8 NONE=0
uint8 FRONT_HAZCAM=1
uint8 REAR_HAZCAM=2
uint8 NAVCAM=3
uint8 MASTCAM=4

# note that mast pointing info below is only valid for navcam or mastcam

# point: specifies pointing direction depending on coordinate frame (below)
geometry_msgs/Point point

# frame: enum specifying coordinate frame in which to apply pointing
uint8 frame
uint8 SITE_XYZ=0
#   point.x = position x in site frame (north, meters)
#   point.y = position y in site frame (east, meters)
#   point.z = position z in site frame (down, meters)
uint8 RNAV_XYZ=1
#   point.x = position x in RNAV frame (rover front, meters)
#   point.y = position y in RNAV frame (rover right, meters)
#   point.z = position z in RNAV frame (rover down, meters)
uint8 LL_ABS_AZEL=2
#   point.x unused
#   point.y = aboslute local level elevation radians (relative to flat)
#   point.z = absolute local level azimuth radians (relative to north)
uint8 LL_REL_AZEL=3
#   point.x unused
#   point.y = radians relative to mast's current local level elevation
#   point.z = radians relative to mast's current local level azimuth
uint8 RNAV_ABS_AZEL=4
#   point.x unused
#   point.y = absolute RNAV elevation radians (relative to rover deck)
#   point.z = absolute RNAV azimuth radians (relative to rover forward)
uint8 RNAV_REL_AZEL=5
#   point.x unused
#   point.y = radians relative to mast's current RNAV elevation
#   point.z = radians relative to mast's current RNAV azimuth

---
################
###  Result  ###
################

# goal_id: should match goal_id assigned by client
actionlib_msgs/GoalID goal_id

# success: true if image was acquired and image/cmod data below is valid
bool success

# left_image: left image data (only relevant if left_camera was not NONE)
sensor_msgs/Image left_image

# left_cmod: left camera model (only relevant if left_camera was not NONE)
sensor_msgs/CameraInfo left_cmod

# right_image: right image data (only relevant if right_camera was not NONE)
sensor_msgs/Image right_image

# right_cmod: right camera model (only relevant if right_camera was not NONE)
sensor_msgs/CameraInfo right_cmod

# rover_pose: rover's pose when image was acquired
geometry_msgs/PoseStamped rover_pose

---
################
### Feedback ###
################

# goal_id: should match goal_id assigned by client
actionlib_msgs/GoalID goal_id

# fraction_complete: percentage of mast pointing motion completed
float32 fraction_complete

# est_completion_time: estimated ROS time when action is expected to be complete
time est_completion_time
