obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.457, 0.305], [0.457, -0.305], [-0.457, -0.305], [-0.457, 0.305]]
inflation_radius: 1.25

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: /lidar/laser/scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: base_link, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
