global_costmap:
  global_frame: /base
  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: false # Since we aren't using a map_server object
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05
