#!/usr/bin/zsh

if [[ -f ~/rover/catkin_ws/launch/rpi.launch ]]; then
    export ROS_MASTER_URI=http://mbr-native:11311
    roslaunch ~/rover/catkin_ws/launch/rpi.launch
else
    echo "Error, camera launch file not found"
    exit 1
fi

