#!/bin/bash

source /opt/ros/jade/setup.bash
source /home/ubuntu/rover/catkin_ws/devel/setup.bash
export ROS_WORKSPACE=/home/ubuntu/rover/catkin_ws
export ROS_PACKAGE_PATH=${ROS_PACKAGE_PATH}:${ROS_WORKSPACE}
export ROS_MASTER_URI=http://david-native:11311

roslaunch /home/ubuntu/rover/catkin_ws/launch/rpi.launch
