#!/usr/bin/zsh

if [[ -f ~/rover/catkin_ws/launch/nuc_cameras.launch ]]; then
    export ROS_MASTER_URI=http://david-native:11311
    roslaunch ~/rover/catkin_ws/launch/nuc_cameras.launch
else
    echo "Error, camera launch file not found"
    exit 1
fi

