#!/usr/bin/zsh

#uvcdynctrl -d `readlink /dev/omnicam` -L "/home/robotics/omnicam_uvc_config"
if [[ -f ~/rover/catkin_ws/launch/nuc_cameras.launch ]]; then
    roslaunch ~/rover/catkin_ws/launch/nuc_cameras.launch
else
    echo "Error, camera launch file not found"
    exit 1
fi

