#!/usr/bin/zsh

if [[ -f ~/rover/catkin_ws/launch/drive-test.launch ]]; then
    roslaunch ~/rover/catkin_ws/launch/drive-test.launch
else
    echo "Error, drive launch file not found"
    exit 1
fi

