#!/usr/bin/zsh

echo "Moving to ROS workspace..."
cd ${ROS_WORKSPACE}
echo

echo "Building workspace..."
catkin_make
echo

echo "Flashing encoder firmware..."
catkin_make arm_tiva_drive_encoder_left_flash
catkin_make arm_tiva_drive_encoder_right_flash
echo

echo "Launching the odometry package..."
echo "TODO."
