#!/usr/bin/zsh

#uvcdynctrl -d `readlink /dev/omnicam` -L "/home/robotics/omnicam_uvc_config"
if [[ -f ~/rover/catkin_ws/launch/arm_cameras.launch ]]; then
    export ROS_MASTER_URI=http://mbr-native:11311
    roslaunch ~/rover/catkin_ws/launch/arm_cameras.launch
else
    echo "Error, camera launch file not found"
    exit 1
fi

