controller_manager_ns: controller_manager
controller_list:
  - name: base_yaw_as
    type: FollowJointTrajectory
    action_ns: /
    default: true
    joints:
      - base_yaw
  - name: base_pitch_as
    type: FollowJointTrajectory
    action_ns: /
    default: true
    joints:
      - base_pitch
  - name: pitch2_as
    type: FollowJointTrajectory
    action_ns: /
    default: true
    joints:
      - pitch2
  - name: roll1_as
    type: FollowJointTrajectory
    action_ns: /
    default: true
    joints:
      - roll1
  - name: pitch3_as
    type: FollowJointTrajectory
    action_ns: /
    default: true
    joints:
      - pitch3
  - name: roll2_as
    type: FollowJointTrajectory
    action_ns: /
    default: true
    joints:
      - roll2
