controller_list:
  - name: fake_Arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - base_yaw
      - base_pitch
      - pitch2
      - roll1
      - pitch3
      - roll2

