controller_list:
  - name: fake_Arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - base_yaw
      - base_pitch
      - elbow_pitch
      - elbow_roll
      - wrist_pitch
      - wrist_roll
