<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="lidar_mount">

    <!-- Constant definitions  -->
    <xacro:property name="width" value="0.1"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="lidar_height" value="0.05"/>
    
    <!-- Import all Gazebo-customization elements, including Gazebo colours -->
    <xacro:include filename="$(find lidar_description)/urdf/lidar.gazebo" />
    <!-- Import Rviz colors -->
    <xacro:include filename="$(find lidar_description)/urdf/materials.xacro" />

    <!-- Base mount link -->
    <link name="base_link">
        <collision>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${base_height}"/>
            </geometry>
        </collision>
        
        <visual>
            <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${base_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>

        <inertial>
            <mass value="0.1"/>
            <inertia ixx="0.001" iyy="0.001" izz="0.001" ixy="0.0" ixz="0.0"
                iyz="0.0"/>
        </inertial>
    </link>

    <!-- The link representing the lidar's mount -->
    <link name="lidar_mount">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${lidar_height/2}"/>
            </geometry>
        </collision>
        
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${lidar_height}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <inertial>
            <mass value="0.1"/>
            <inertia ixx="0.001" iyy="0.001" izz="0.001" ixy="0.0" ixz="0.0"
                iyz="0.0"/>
        </inertial>
    </link>

    <!-- The joint which allows rotation for the lidar -->
    <joint name="tilt_lidar" type="continuous">
        <parent link="base_link"/>
        <child link="lidar_mount"/>
        <origin xyz="0 0 ${base_height+lidar_height/2}" rpy="0 0 0"/>
        <!-- Allows tilting around the Y axis" -->
        <axis xyz="0 1 0"/>
    </joint>

    <!-- The joint affixing the laser to the tilt_lidar platform -->
    <joint name="hokuyo_joint" type="fixed">
        <axis xyz="0 1 0" />
        <origin xyz="0 0 ${lidar_height}" rpy="0 0 0"/>
        <parent link="lidar_mount"/>
        <child link="hokuyo_link"/>
    </joint>

    <!-- Hokuyo Laser -->
    <link name="hokuyo_link">
        <collision>
      	    <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://lidar_description/meshes/hokuyo.dae"/>
            </geometry>
        </visual>

        <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
    </link>
</robot>
