
#ifndef ROVER_ARDUINO_PINS_AUGER_H
#define ROVER_ARDUINO_PINS_AUGER_H

// Pins need to be adjusted
#define PIN_AUGER_SERVO 7
#define PIN_ROCK_SERVO 9
#define PIN_SOIL_SERVO 11

#define PIN_AUGER_VERTICAL_VELOCITY_INA 36
#define PIN_AUGER_VERTICAL_VELOCITY_INB 37
#define PIN_AUGER_VERTICAL_VELOCITY_PWM 3

#define PIN_AUGER_ANGULAR_VELOCITY_INA 26
#define PIN_AUGER_ANGULAR_VELOCITY_INB 27
#define PIN_AUGER_ANGULAR_VELOCITY_PWM 2

#define PIN_LIMIT_SWITCH_UP 8
#define PIN_LIMIT_SWITCH_DOWN 12

#endif //ROVER_ARDUINO_PINS_AUGER_H
