
#ifndef ROVER_ARDUINO_PINS_AUGER_H
#define ROVER_ARDUINO_PINS_AUGER_H

#define PIN_AUGER_POSITION_INA 6 
#define PIN_AUGER_POSITION_INB 4
#define PIN_AUGER_POSITION_PWM 5

#define PIN_AUGER_VELOCITY_INA 2 
#define PIN_AUGER_VELOCITY_INB 7 
#define PIN_AUGER_VELOCITY_PWM 3 

#define PIN_TEMP_PROB_POSITION 13

#define PIN_GATE_POSITION_INA 8
#define PIN_GATE_POSITION_INB 10
#define PIN_GATE_POSITION_PWM 9

#define PIN_LIMIT_SWITCH_UP 12
#define PIN_LIMIT_SWITCH_DOWN 11
#define PIN_LIMIT_SWITCH_PROB A2 //A2
#define PIN_LIMIT_SWITCH_GATE A3 //A3

#endif //ROVER_ARDUINO_PINS_AUGER_H
