
#ifndef ROVER_ARDUINO_PINS_AUGER_H
#define ROVER_ARDUINO_PINS_AUGER_H

#define PIN_AUGER_VERTICAL_VELOCITY_INA 9
#define PIN_AUGER_VERTICAL_VELOCITY_INB 4
#define PIN_AUGER_VERTICAL_VELOCITY_PWM 5

#define PIN_AUGER_ANGULAR_VELOCITY_INA 2
#define PIN_AUGER_ANGULAR_VELOCITY_INB 7
#define PIN_AUGER_ANGULAR_VELOCITY_PWM 3

#define PIN_TEMP_PROB_POSITION 11

#define PIN_GATE_POSITION_INA 8
#define PIN_GATE_POSITION_INB 10
#define PIN_GATE_POSITION_PWM 6

#define PIN_LIMIT_SWITCH_UP A2
#define PIN_LIMIT_SWITCH_DOWN 13
#define PIN_LIMIT_SWITCH_PROB A3 //A2

#endif //ROVER_ARDUINO_PINS_AUGER_H
